functionsDirectory = "/Users/evertonbuzzi/Dev/signal-news-agent/netlify/functions"
functionsDirectoryOrigin = "config"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "/Users/evertonbuzzi/Dev/signal-news-agent/webapp/dist"
publishOrigin = "config"
commandOrigin = "config"
command = "yarn build"
base = "/Users/evertonbuzzi/Dev/signal-news-agent/webapp"
functions = "/Users/evertonbuzzi/Dev/signal-news-agent/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]